### PR TITLE
fix: clean up action.openattestation trailing slash and git repository warning

### LINKED ISSUE #157: tradetrust-website@2.0.0 No repository field
While running npm install, i encounter a warning message "tradetrust-website@2.0.0 No repository field". May I know what action is required for this?

### PR DESCRIPTION
**Pull request by justussoh**
This PR fixes:
1. QR code uri has inconsistent standards with trailing slashes, removed all trailing slash! (regex test still makes it compatible with past standards)
1. also add repository field in package.json to remove warning

### CODE REVIEW

**Review by simboonlong — APPROVED** [review]

File: src/components/QrReader/Scanner.js [hunk 1]
```diff
@@ -1,6 +1,7 @@
 import { useLayoutEffect } from "react";
 import QrScanner from "qr-scanner";
 import QrScannerWorkerPath from "!!file-loader!../../../node_modules/qr-scanner/qr-scanner-worker.min.js";
+// `!!file-loader!` explicitly instruct webpack to import file with file-loader overwriting global config
```
Comment (Nebulis) [inline src/components/QrReader/Scanner.js:3]: usually the comment is added before because we read from top to bottom :eyes:

**Review by Nebulis — APPROVED** [review]
