### PR TITLE
fix: update testcafe local

### LINKED ISSUE #631: local fixtures
after https://github.com/TradeTrust/tradetrust-website/pull/629, perhaps we should look into setup of fixtures in local blockchain instead, so to futureproof any testnet migration again

### PR DESCRIPTION
**Pull request by isaackps**
## Summary

Remove Goerli testnets dependencies and move e2e testcafe testing to local.

## Changes

- update ganache for local e2e testcafe testing
- update default to sepolia, and update some ui test for sepolia
- update all fixtures to use on local with a setup script
- update ci script to use local env
- update existing endorsement chain test to use mumbai ebl document that is stored in gallery instead.

## Issues
Deprecation of goerli testnet on TT- web
https://www.pivotaltracker.com/story/show/184904312

### CODE REVIEW

File: .storybook/main.js [hunk 1]
```diff
@@ -21,7 +21,18 @@ module.exports = {
...
+    const directoryPath = path.resolve(__dirname).replace(".storybook", "");
+
+    config.module.rules.push({
+      test: /\.(ts|js)x?$/,
+      include: [directoryPath, directoryPath.concat("node_modules/web-did-resolver")],
+      use: {
+        loader: "babel-loader",
+      },
+    });
+
```
Comment (cavacado) [inline .storybook/main.js:35]: was wondering if we could import the project's webpackconfig file and then only use this part of it when patching this storybook's webpack config

**Review by cavacado — COMMENTED** [review]
have discussed on some changes:
1.  moving "http://localhost:8545" to a readable const .
2. addition of option of using env config ALCHEMY_API_KEY, ow default to this key.
3. requested removal of unwrapped local demo tt doc

will refine further once these changes have been addressed.
would be better if you get 1 more person's to look at this but overall should be fine.

File: .storybook/main.js (hunk 1 above)
Comment (isaackps) [reply .storybook/main.js:35]: understand that, but i dont think able to do so.

**Comment by isaackps** [comment]
can someone help me update the Lint & Test expected report status from settings?

File: .github/workflows/testcafe.yml [hunk 2]
```diff
@@ -13,17 +13,12 @@ jobs:
...
-      - name: Check Lint
-        run: npm run lint
-      - name: Test
-        if: ${{ !contains(github.event.head_commit.message, '[skip test]') }}
-        run: npm run test
       - name: Build
         run: npm run build:test
       - name: Integration - testcafe
         id: testcafe
         if: ${{ !contains(github.event.head_commit.message, '[skip test]') }}
```
Comment (simboonlong) [inline .github/workflows/testcafe.yml:20]: shift to most top to skip all immediately when condition met

File: .storybook/main.js [hunk 3]
```diff
@@ -21,7 +21,18 @@ module.exports = {
...
   },
-  webpackFinal: (config) => {
+  webpackFinal: async (config) => {
+    // need to include this web-did-resolver module into babel-loader to convert it from using esm to commonjs
+    const directoryPath = path.resolve(__dirname).replace(".storybook", "");
+
+    config.module.rules.push({
+      test: /\.(ts|js)x?$/,
+      include: [directoryPath, directoryPath.concat("node_modules/web-did-resolver")],
+      use: {
```
Comment (simboonlong) [inline .storybook/main.js:31]: just curious, what did `web-did-resolver` cause say if this is not included?

File: package.json [hunk 4]
```diff
@@ -8,11 +8,11 @@
...
   "scripts": {
     "blockchain": "ganache --wallet.mnemonic \"indicate swing place chair flight used hammer soon photo region volume shuffle\" -i 1337",
-    "blockchain:contracts": "node --experimental-modules ./tests/e2e/setup-contracts.mjs",
-    "blockchain:testrun": "concurrently -k -s first \"npm:blockchain\" \"npm:blockchain:contracts\"",
+    "blockchain:contracts:synpress": "node --experimental-modules ./tests/e2e/setup-contracts.mjs",
+    "blockchain:contracts:testcafe": "node --experimental-modules ./src/test/setup-contracts-testcafe.mjs",
     "build": "run-s check-types build:css build:app",
     "build:dev": "cross-env NODE_ENV=development npm run build",
-    "build:test": "cross-env NODE_ENV=test NET=goerli npm run build",
+    "build:test": "cross-env NET=local npm run build",
```
Comment (simboonlong) [inline package.json]: why is NODE_ENV=test removed?

File: package.json [hunk 5]
```diff
@@ -25,7 +25,9 @@
     "integration:single": "testcafe chrome -L",
     "integration:headless:prod": "testcafe --config-file \".testcaferc-prod.json\"",
     "integration:headless:dev": "testcafe --config-file \".testcaferc-dev.json\"",
-    "integration:metamask": "run-s wait blockchain:contracts integration:synpress",
+    "integration:testcafe": "run-s blockchain:contracts:testcafe integration:headless:prod",
```
Comment (simboonlong) [inline package.json]:
```suggestion
    "integration:testcafe": "run-s blockchain:contracts:testcafe integration:testcafe:prod",
```
to align with the renames?

File: src/common/hooks/useEndorsementChain/fetchEscrowTransfer.integration.test.ts [hunk 6]
```diff
@@ -1,115 +1,73 @@
 import { ethers, providers } from "ethers";
 import { useProviderContext } from "../../contexts/provider";
-import { INFURA_API_KEY } from "../../../config";
+import { ALCHEMY_API_KEY } from "../../../config";
```
Comment (simboonlong) [inline src/common/hooks/useEndorsementChain/fetchEscrowTransfer.integration.test.ts:3]: just curious, why the switch to alchemy?

File: src/common/hooks/useEndorsementChain/fetchEscrowTransfer.integration.test.ts [hunk 7]
```diff
@@ -1,115 +1,73 @@
...
 import { TitleEscrow__factory } from "@govtechsg/token-registry/dist/contracts";
 import { fetchEscrowTransfers, fetchHolderTransfers, fetchOwnerTransfers, getParsedLogs } from "./fetchEscrowTransfer";
 
 jest.mock("../../contexts/provider");
 
-const goerliProvider = new ethers.providers.InfuraProvider("goerli", INFURA_API_KEY);
+const mumbaiProvider = new ethers.providers.AlchemyProvider("maticmum", ALCHEMY_API_KEY);
```
Comment (simboonlong) [inline src/common/hooks/useEndorsementChain/fetchEscrowTransfer.integration.test.ts:9]: just curious, why maticmum and not sepolia?

File: src/config/index.js [hunk 8]
```diff
@@ -18,6 +18,7 @@ module.exports = {
   },
   INFURA_API_KEY: process.env.INFURA_API_KEY || "bb46da3f80e040e8ab73c0a9ff365d18",
   INFURA_PROJECT_ID: "1f1ff2b3fca04f8d99f67d465c59e4ef",
+  ALCHEMY_API_KEY: process.env.ALCHEMY_API_KEY || "pV9JmoYcDFFBihXlJWt6FSDxzNAVWxdT",
   IS_DEVELOPMENT,
```
Comment (simboonlong) [inline src/config/index.js:22]: i presume this is to a dashboard where the api key is generated. do we have login access to this dashboard?

File: src/test/setup-contracts-testcafe.mjs [hunk 9]
```diff
@@ -0,0 +1,104 @@
...
+  `${oaCLI_PATH} title-escrow accept-surrendered --token-registry ${TOKEN_REGISTRY_ADDRESS} --tokenId ${MERKLE_ROOT_OF_ENDORSEMENT_CHAIN_DOCUMENT} -n local -k ${ACCOUNT_KEY}`
+);
+
+// prep for issuing document store
+const merkleRootToIssue = [
+  // demo document - local.tt
+  "0xd7a0c43098da5bcabd2093f6f1d8c35d6d898a2a0a17d92d3d1bf0c1845aa6a6",
+  // invoice-attachments.json
+  "0x927c044be8438b3f042ca4edb601269db115a67ae0bf5abeb9ae38695a002d4d",
+  // invoice-missing-renderer-url.json
```
Comment (simboonlong) [inline src/test/setup-contracts-testcafe.mjs:78]: is there a way to import the hashes from the fixtures instead?

File: .storybook/main.js (hunk 3 above)
Comment (isaackps) [reply .storybook/main.js:31]: it will load the esm version, and it cant compile. So need to include it so that babel will do its thing to compile it properly.

File: package.json (hunk 4 above)
Comment (isaackps) [reply package.json]: ya right, should not be removed, must be my mistake, good catch. will put it back in.

File: package.json (hunk 5 above)
Comment (isaackps) [reply package.json]: ok sure

File: src/common/hooks/useEndorsementChain/fetchEscrowTransfer.integration.test.ts (hunk 6 above)
Comment (isaackps) [reply src/common/hooks/useEndorsementChain/fetchEscrowTransfer.integration.test.ts:3]: the infura need to be enabled for polygon, but cant do it at the moment, I asked PH about it, so use a free account in alchemy instead.

File: src/common/hooks/useEndorsementChain/fetchEscrowTransfer.integration.test.ts (hunk 7 above)
Comment (isaackps) [reply src/common/hooks/useEndorsementChain/fetchEscrowTransfer.integration.test.ts:9]: since sepolia has a end of life date and maticmum dont, at the moment, thats y i go for maticmum so when sepolia die, we wont have to update it again.

File: src/config/index.js (hunk 8 above)
Comment (isaackps) [reply src/config/index.js:22]: currently its i am the one that created this api key, i talked to ZL and he said that we can use this for the time being and generate one with the govtech email in future.

File: src/test/setup-contracts-testcafe.mjs (hunk 9 above)
Comment (isaackps) [reply src/test/setup-contracts-testcafe.mjs:78]: would it be more troublesome?

File: .github/workflows/testcafe.yml (hunk 2 above)
Comment (isaackps) [reply .github/workflows/testcafe.yml:20]: ok

Comment (simboonlong) [reply .github/workflows/testcafe.yml:20]: sorry actually maybe no, let's leave this. as we still need to marked this as required in settings later

File: src/config/index.js (hunk 8 above)
Comment (simboonlong) [reply src/config/index.js:22]: maybe let me create 1 with dlt gmail. let u noe again

Comment (simboonlong) [reply src/config/index.js:22]: created and added in netlify variable, can leave yours there as fallback

File: .github/workflows/testcafe.yml (hunk 2 above)
Comment (isaackps) [reply .github/workflows/testcafe.yml:20]: ok wont do the changes.

**Review by simboonlong — APPROVED** [review]
