### PR TITLE
Feat/qr scanner fix

### LINKED ISSUE #229: bug: unable to open qr code from scanner on tradetrust.io website
Scanner not updated for the new QR format. Scanning does nothing.

Inputs
[ebl-with-qrcode.txt](https://github.com/TradeTrust/tradetrust-website/files/5159836/ebl-with-qrcode.4.txt)
[printed qrcode.pdf](https://github.com/TradeTrust/tradetrust-website/files/5159839/printed.qrcode.pdf)

Expected
Document to open on scan

### PR DESCRIPTION
**Pull request by justussoh**
This PR updates:
1. QrReader to read new action link schema from QRCode
2. Updates the QRScanner from `react-qr-reader`(not maintained) to `qr-scanner`(maintained, based on google qr reader library)

To test this pr:
- scan any tt file with qrcode
-  Use the following qrcode
Screenshot 2020-10-14 at 3 11 13 PM

### CODE REVIEW

File: src/services/qrProcessor/index.js [hunk 1]
```diff
@@ -1,38 +1,49 @@
-import { get } from "axios";
+import axios from "axios";
 import { decryptString } from "@govtechsg/oa-encryption";
 
 export const decodeQrCode = (qrCode) => {
-  const ttRegex = /tradetrust:\/\/(.*)/;
+  const ttRegex = /https:\/\/action.openattestation.com\/\?q=(.*)/;
```
Comment (rjchow) [inline src/services/qrProcessor/index.js]:
```suggestion
  const openAttestationActionRegex = /https:\/\/action.openattestation.com\/\?q=(.*)/;
```

File: src/services/qrProcessor/index.js [hunk 2]
```diff
@@ -1,38 +1,49 @@
...
   if (!ttRegex.test(qrCode)) throw new Error("QR Code is not formatted to TradeTrust specifications");
   const [, encodedPayload] = ttRegex.exec(qrCode);
   const decodedPayload = JSON.parse(decodeURIComponent(encodedPayload));
   return decodedPayload;
 };
 
-export const encodeQrCode = (payload) => `tradetrust://${encodeURIComponent(JSON.stringify(payload))}`;
+export const encodeQrCode = (payload) =>
```
Comment (rjchow) [inline src/services/qrProcessor/index.js]: this is weird to see here, do we even use this outside of tests?

File: src/services/qrProcessor/index.js [hunk 3]
```diff
@@ -1,38 +1,49 @@
...
-const decryptDocument = async (uri) => {
-  try {
-    const uriPart = uri.split("#");
-    const { data } = await get(uriPart[0]);
-    return JSON.parse(
+const decryptQuery = async (action) => {
+  if (action.type !== "DOCUMENT") throw new Error(`The type ${action.type} provided from the action is not supported`);
+  const { uri, key } = action.payload;
+  const response = await axios.get(uri);
+  if (response.status >= 400 && response.status < 600) throw new Error(`Unable to load the certificate from ${uri}`);
```
Comment (rjchow) [inline src/services/qrProcessor/index.js]: p sure axios just throws error if status != 2xx ? just because git blame says laurent doesn't mean its correct :D

Comment (rjchow) [reply src/services/qrProcessor/index.js]: https://github.com/axios/axios#handling-errors

File: src/services/qrProcessor/index.js [hunk 4]
```diff
@@ -1,38 +1,49 @@
...
-export const encodeQrCode = (payload) => `tradetrust://${encodeURIComponent(JSON.stringify(payload))}`;
+export const encodeQrCode = (payload) =>
+  `https://action.openattestation.com/?q=${encodeURIComponent(JSON.stringify(payload))}`;
 
-const decryptDocument = async (uri) => {
-  try {
-    const uriPart = uri.split("#");
-    const { data } = await get(uriPart[0]);
-    return JSON.parse(
+const decryptQuery = async (action) => {
```
Comment (rjchow) [inline src/services/qrProcessor/index.js]: does the function name reflect what is happening in the body?

File: src/services/qrProcessor/index.js (hunk 2 above)
Comment (justussoh) [reply src/services/qrProcessor/index.js]: Nope, we don't so how should we fix this?

Comment (rjchow) [reply src/services/qrProcessor/index.js]: just delete this declaration and hardcode it into test cases

**Review by rjchow — APPROVED** [review]
