### PR TITLE
fix: endorsement chain error for call revert exception

### LINKED ISSUE #283: bug: Direct transferTo call can cause an error in the Endorsement Chain
**Description:**
The [following](https://github.com/Open-Attestation/token-registry/blob/master/contracts/TitleEscrow.sol#L142) call can cause the Endorsement Chain to break.

**How to reproduce:**
- Execute a direct token transfer on a eBL with the [following](https://github.com/Open-Attestation/token-registry/blob/master/contracts/TitleEscrow.sol#L142) call
- Upload the eBL in the tradetrust site
- View Endorsement Chain
- The following will show up:

Screenshot from 2020-11-25 12-14-40

I can also provide you with the .tt I used, if that is easier?

I did look at the [code](https://github.com/TradeTrust/tradetrust-website/blob/master/src/common/hooks/useEndorsementChain/useEndorsementChain.ts), and noticed that it looks for the following three states: Transfer, Surrender, Burnt. Only when the  [following](https://github.com/Open-Attestation/token-registry/blob/master/contracts/TitleEscrow.sol#L142) call is used, then it is not reaching either of those three states, resulting in the error.

**Possible solution:**
Support a state of the direct token transfer call in the Endorsement Chain

Came across this by chance, thought this might be helpful!

### PR DESCRIPTION
**Pull request by dhemutton**
This PR is for the story: https://www.pivotaltracker.com/story/show/175903430 and the issue: https://github.com/TradeTrust/tradetrust-website/issues/283#issue-750763834

The bug occurs due to a call revert exception being thrown by the `supportsInterface` method when the title escrow is transferred to the owner. A new state `Transfer to Wallet` was added and updates to the UI was also made to handle the change of the new state. The attached .txt can be converted to a .tt file to be tested.

Screenshot 2020-11-26 at 7 31 57 PM

[test.txt](https://github.com/TradeTrust/tradetrust-website/files/5602637/test.txt)

### CODE REVIEW

File: src/common/hooks/useEndorsementChain/fetchEscrowTransfer.ts [hunk 1]
```diff
@@ -54,3 +54,19 @@ export const fetchEventInfo = async (
...
+export const fetchEvents = async (
+  address: string,
+  blockNumber: number,
+  provider: providers.Provider
+): Promise<TradeTrustErc721Event> => {
+  try {
+    return await fetchEscrowTransfers(address, provider);
+  } catch (e) {
+    //SupportsInterface throws a call revert exception when the owner is a wallet
+    if (e.message.includes("call revert exception")) {
```
Comment (yehjxraymond) [inline src/common/hooks/useEndorsementChain/fetchEscrowTransfer.ts]: This is actually a very generic error. The reason this error happens is that it tries to query that address as if its a smart contract but when it calls `supportsInterface` it fails. This means that this function has a hidden coupling with the order of the calls in the above function. An example of how this flow could fail:

The address is a smart contract that has the supported interface, but for some reason maybe the `beneficiary` method throws call revert because it is not implemented. Now this code will assume that the contract is an EOA.

A better way to do this is to check if the address has code, u can do this via `provider.getCode` i think. If there is no code, you know for sure it is not a smart contract and may assume that its "Transferred to wallet". If there is code, then just proceed to `fetchEscrowTransfers`

**Review by yehjxraymond — APPROVED** [review]
lgtm (=
