### PR TITLE
fix: addressname resolve rebase 91

### LINKED ISSUE #44: Display loader/spinner while fetching owner of the token

### PR DESCRIPTION
**Pull request by simboonlong**
- load addresses without login into metamask
- resolve addresses names by uploading csv file
- add skeleton loader to addresses
- change ReactElement type to React.ReactNode type
- enable addressbook feature-toggle for e2e test
- add prep task in package.json

### CODE REVIEW

File: src/components/AddressBook/CsvUploadButton.tsx [hunk 1]
```diff
@@ -2,6 +2,7 @@ import React from "react";
 import web3 from "web3";
```
Comment (Nebulis) [inline src/components/AddressBook/CsvUploadButton.tsx:2]: dont forget to change the base to master :)

**Comment by yehjxraymond** [comment]
image

File: src/components/AddressBook/CsvUploadButton.tsx [hunk 2]
```diff
@@ -43,18 +44,22 @@ export const CsvUploadButton = () => {
...
-        onChange={handleUploadedFile}
-        style={{ display: "none" }}
-        accept=".csv"
-      />
-      <label className="p-3" style={{ cursor: "pointer" }} htmlFor="csv-file-input">
-        Upload Address Book
-      </label>
+    <div className="my-auto ml-2">
+      <ButtonBordered color="tertiary">
+        <>
```
Comment (yehjxraymond) [inline src/components/AddressBook/CsvUploadButton.tsx]: why need fragments here?

File: src/components/TitleTransferPanel/TitleTransferPanel.tsx [hunk 3]
```diff
@@ -2,7 +2,11 @@ import React from "react";
 import { LabelBordered } from "../UI/LabelBordered";
 import { TitleTransferPanelContent } from "./TitleTransferPanelContent";
 
-export const TitleTransferPanel = () => {
+interface TitleTransferPanelProps {
+  document: object;
```
Comment (yehjxraymond) [inline src/components/TitleTransferPanel/TitleTransferPanel.tsx]: Please type this.

File: src/components/TitleTransferPanel/TitleTransferPanelContent/TitleTransferPanelContent.tsx [hunk 4]
```diff
@@ -1,21 +1,50 @@
...
-  const { holderAddress, beneficiaryAddress } = useSelector((state: any) => ({
-    holderAddress: state.token.holderAddress,
-    beneficiaryAddress: state.token.beneficiaryAddress
-  }));
+interface TitleTransferPanelContentProps {
+  document: object;
+}
+
+export const TitleTransferPanelContent = ({ document }: TitleTransferPanelContentProps) => {
+  const [tokenError, setError] = useState(null);
```
Comment (yehjxraymond) [inline src/components/TitleTransferPanel/TitleTransferPanelContent/TitleTransferPanelContent.tsx]: why need null? 

```suggestion
  const [tokenError, setError] = useState();
```

File: src/components/TitleTransferPanel/TitleTransferPanelContent/TitleTransferPanelContent.tsx [hunk 5]
```diff
@@ -1,21 +1,50 @@
...
+  const [tokenOwner, setTokenOwner] = useState("");
+  const { holderAddress, beneficiaryAddress } = useEscrowContractUsers({ escrowContractAddress: tokenOwner });
+
+  const isToken = isERC721Token(document);
+  useEffect(() => {
+    async function fetchTokenOwner() {
```
Comment (yehjxraymond) [inline src/components/TitleTransferPanel/TitleTransferPanelContent/TitleTransferPanelContent.tsx]: Why need this, shouldnt this be handled within `useEscrowContractUsers`?

File: src/components/TitleTransferPanel/TitleTransferPanelContent/TitleTransferPanelContent.tsx [hunk 6]
```diff
@@ -1,21 +1,50 @@
...
+      try {
+        const owner = await getTokenOwner({ document });
+        trace(`Token Owner: ${owner}`);
+        setTokenOwner(owner);
+      } catch (e) {
+        error(`error in fetching token owner: ${JSON.stringify(e)}`);
+        setError(e.message);
+      }
+    }
+    if (isToken) fetchTokenOwner();
```
Comment (yehjxraymond) [inline src/components/TitleTransferPanel/TitleTransferPanelContent/TitleTransferPanelContent.tsx]: why is this inside useEffect?

File: src/components/TitleTransferPanel/TitleTransferPanelContent/TitleTransferPanelContent.tsx [hunk 7]
```diff
@@ -1,21 +1,50 @@
...
+  }, [document, isToken]);
+
+  if (!isToken) return null;
```
Comment (yehjxraymond) [inline src/components/TitleTransferPanel/TitleTransferPanelContent/TitleTransferPanelContent.tsx]: If it's not a token this panel wont even be displayed right? no need short circuit

File: src/components/TitleTransferPanel/TitleTransferPanelContent/TitleTransferPanelContent.tsx [hunk 8]
```diff
@@ -1,21 +1,50 @@
...
 
   return (
     <>
       <div className="row">
         {(holderAddress || beneficiaryAddress) && (
           <div className="col-12 col-lg">
-            <TitleView role="Beneficiary" address={beneficiaryAddress} />
-            <TitleView role="Holder" address={holderAddress} />
+            {tokenError ? (
```
Comment (yehjxraymond) [inline src/components/TitleTransferPanel/TitleTransferPanelContent/TitleTransferPanelContent.tsx]: Why couple `tokenError` with the two fields? Can just display tokenError if any.

File: src/test/fixture/addressbook/Maersk Bill of Lading.tt [hunk 9]
```diff
@@ -0,0 +1,58 @@
+{
```
Comment (yehjxraymond) [inline src/test/fixture/addressbook/Maersk Bill of Lading.tt]: Should this file be inside this folder? We may not have to put the .csv file in /addressbook as well. Can move them one level up.

**Review by yehjxraymond — COMMENTED** [review]
Can write an e2e test to test out the workflow.

File: src/components/TitleTransferPanel/TitleTransferPanel.tsx (hunk 3 above)
Comment (simboonlong) [reply src/components/TitleTransferPanel/TitleTransferPanel.tsx]: how do i go about doing for this case?

Comment (yehjxraymond) [reply src/components/TitleTransferPanel/TitleTransferPanel.tsx]: There's the types in the OA package. See:

https://github.com/Open-Attestation/open-attestation/blob/master/src/%40types/document.ts
https://github.com/Open-Attestation/oa-verify/blob/master/src/verifiers/verificationBuilder.ts

File: src/components/TitleTransferPanel/TitleTransferPanelContent/TitleTransferPanelContent.tsx [hunk 10]
```diff
@@ -1,23 +1,34 @@
...
     <>
       <div className="row">
-        {(holderAddress || beneficiaryAddress) && (
-          <div className="col-12 col-lg">
-            <TitleView role="Beneficiary" address={beneficiaryAddress} />
-            <TitleView role="Holder" address={holderAddress} />
-          </div>
-        )}
+        <div className="col-12 col-lg">
+          <TitleView id="beneficiary" role="Beneficiary" address={beneficiaryAddress} />
```
Comment (yehjxraymond) [inline src/components/TitleTransferPanel/TitleTransferPanelContent/TitleTransferPanelContent.tsx]: Why need an id here that is passed a few levels deep? Possible to use other selector using numbered ones? 

Seemed like there's the `nth` selector
image

File: src/components/TitleTransferPanel/AddressInfo/AddressInfo.tsx [hunk 11]
```diff
@@ -2,14 +2,15 @@ import React, { ReactElement } from "react";
...
   title: string;
   name?: string;
   children: ReactElement;
 }
 
-export const AddressInfo = ({ title, name, children }: AddressInfoProps) => {
+export const AddressInfo = ({ id, title, name, children }: AddressInfoProps) => {
   return (
-    <div className={`${css["address-info"]}`}>
+    <div id={id} className={`${css["address-info"]}`}>
```
Comment (yehjxraymond) [inline src/components/TitleTransferPanel/AddressInfo/AddressInfo.tsx]: No point passing id

File: src/components/TitleTransferPanel/TitleTransferPanelContent/TitleTransferPanelContent.tsx [hunk 12]
```diff
@@ -1,23 +1,34 @@
...
+
+export const TitleTransferPanelContent = ({ document }: TitleTransferPanelContentProps) => {
+  const [tokenOwnerAddress, setTokenOwnerAddress] = useState("");
+  const { holderAddress, beneficiaryAddress } = useEscrowContractUsers({ escrowContractAddress: tokenOwnerAddress });
+  const fetchTokenOwner = async () => {
+    try {
+      const address = await getTokenOwner({ document });
+      setTokenOwnerAddress(address);
+    } catch (e) {
+      console.log(e.message);
```
Comment (yehjxraymond) [inline src/components/TitleTransferPanel/TitleTransferPanelContent/TitleTransferPanelContent.tsx]: if you are not gonna act on it, let it crash, no need to log

Comment (yehjxraymond) [reply src/components/TitleTransferPanel/TitleTransferPanelContent/TitleTransferPanelContent.tsx]: this way it will fail silently

File: src/components/TitleTransferPanel/TitleView/TitleView.tsx [hunk 13]
```diff
@@ -1,23 +1,24 @@
...
+export const TitleView = ({ id, role, address }: TitleViewProps) => {
   const addressHref = makeEtherscanAddressURL(address);
-  const issuerName = get(registry.issuers, `${address}`) ? get(registry.issuers, `${address}`).name : null;
+  const { getIdentifier } = useAddressBook();
+  const name = getIdentifier(address);
 
   return (
     <div className={css["title-view"]}>
-      <AddressInfo title={role} name={issuerName}>
+      <AddressInfo id={id} title={role} name={name}>
```
Comment (yehjxraymond) [inline src/components/TitleTransferPanel/TitleView/TitleView.tsx]: no need id

File: src/components/UI/ExternalLink/ExternalLink.tsx [hunk 14]
```diff
@@ -7,8 +7,12 @@ interface ExternalLinkProps {
 
 export const ExternalLink = ({ name, href }: ExternalLinkProps) => {
   return (
-    <a href={href} target="_blank" rel="noopener noreferrer">
-      {name}
-    </a>
+    <>
```
Comment (yehjxraymond) [inline src/components/UI/ExternalLink/ExternalLink.tsx]: why fragment?

File: src/test/load-addressbook.spec.js [hunk 15]
```diff
@@ -0,0 +1,28 @@
...
+const validateTextContent = async (t, component, texts) =>
+  texts.reduce(async (prev, curr) => t.expect(component.textContent).contains(curr), Promise.resolve());
+
+test("AddressBook local names to be resolved correctly", async t => {
+  await t.setFilesToUpload("input[type=file]", [Document]);
+  await TitleTransferPanel.with({ visibilityCheck: true })();
+  await validateTextContent(t, StatusButton, ["Issued by TRADETRUST.IO"]);
+
+  const elExists = await CSVFileInput.exists;
+  if (elExists) {
```
Comment (yehjxraymond) [inline src/test/load-addressbook.spec.js]: why only if csv input exist? if it's because of the env?

Comment (simboonlong) [reply src/test/load-addressbook.spec.js]: yeah, passed in local but failing here. i tried timeout also cant work. putting the exists somehow passed here

File: src/components/UI/ExternalLink/ExternalLink.tsx (hunk 14 above)
Comment (simboonlong) [reply src/components/UI/ExternalLink/ExternalLink.tsx]: Screenshot 2020-03-24 at 4 09 25 PM

if i nv put i getting this warning from ts, maybe let me tweak abit

Comment (simboonlong) [reply src/components/UI/ExternalLink/ExternalLink.tsx]: ok i found out the problem, i should use `children: React.ReactNode;` instead of `children: ReactElement;`, will update

File: src/components/TitleTransferPanel/TitleTransferPanelContent/TitleTransferPanelContent.tsx (hunk 10 above)
Comment (simboonlong) [reply src/components/TitleTransferPanel/TitleTransferPanelContent/TitleTransferPanelContent.tsx]: okay 👌

File: src/test/load-addressbook.spec.js (hunk 15 above)
Comment (simboonlong) [reply src/test/load-addressbook.spec.js]: wait, then i couldn't tell too if the csvfile upload test is working here, lol

File: src/components/TitleTransferPanel/TitleTransferPanelContent/TitleTransferPanelContent.tsx [hunk 16]
```diff
@@ -1,23 +1,32 @@
...
+}
+
+export const TitleTransferPanelContent = ({ document }: TitleTransferPanelContentProps) => {
+  const [tokenOwnerAddress, setTokenOwnerAddress] = useState("");
+  const { holderAddress, beneficiaryAddress } = useEscrowContractUsers({ escrowContractAddress: tokenOwnerAddress });
+  const fetchTokenOwner = async () => {
+    try {
+      const address = await getTokenOwner({ document });
+      setTokenOwnerAddress(address);
+    } catch (e) {}
```
Comment (yehjxraymond) [inline src/components/TitleTransferPanel/TitleTransferPanelContent/TitleTransferPanelContent.tsx]: Dont even catch, this will make it fail even more silently

File: src/components/TitleTransferPanel/TitleView/TitleView.tsx [hunk 17]
```diff
@@ -13,12 +12,13 @@ interface TitleViewProps {
...
-  const issuerName = get(registry.issuers, `${address}`) ? get(registry.issuers, `${address}`).name : null;
+  const { getIdentifier } = useAddressBook();
+  const name = getIdentifier(address);
 
   return (
     <div className={css["title-view"]}>
-      <AddressInfo title={role} name={issuerName}>
-        <ExternalLink name={address} href={addressHref} />
+      <AddressInfo title={role} name={name}>
+        {address && <ExternalLink name={address} href={addressHref} />}
```
Comment (yehjxraymond) [inline src/components/TitleTransferPanel/TitleView/TitleView.tsx:21]: why need to assert address? in the props it shows that it's always present

File: src/test/load-addressbook.spec.js (hunk 15 above)
Comment (yehjxraymond) [reply src/test/load-addressbook.spec.js]: yea, if its not running the test then it will just fail silently, you want to find out why it fails. Is it because the feature is hidden away?

File: src/components/TitleTransferPanel/TitleView/TitleView.tsx (hunk 17 above)
Comment (simboonlong) [reply src/components/TitleTransferPanel/TitleView/TitleView.tsx:21]: mmm cos for bene and holder address they are being fetched asynchronously, i wanted it not to render anything at all so that the skeleton css :empty will work as expected

File: src/test/load-addressbook.spec.js (hunk 15 above)
Comment (simboonlong) [reply src/test/load-addressbook.spec.js]: oh ya i think so, the feature toggle. let me try enable it

Comment (simboonlong) [reply src/test/load-addressbook.spec.js]: yeah, enable passed liao

File: src/components/TitleTransferPanel/TitleTransferPanelContent/TitleTransferPanelContent.tsx [hunk 18]
```diff
@@ -1,23 +1,34 @@
...
-  }));
+interface TitleTransferPanelContentProps {
+  document: WrappedDocument;
+}
+
+export const TitleTransferPanelContent = ({ document }: TitleTransferPanelContentProps) => {
+  const [tokenOwnerAddress, setTokenOwnerAddress] = useState("");
+  const { holderAddress, beneficiaryAddress } = useEscrowContractUsers({ escrowContractAddress: tokenOwnerAddress });
+  const fetchTokenOwner = async () => {
+    try {
```
Comment (yehjxraymond) [inline src/components/TitleTransferPanel/TitleTransferPanelContent/TitleTransferPanelContent.tsx]: do not even try LOL

Comment (yehjxraymond) [reply src/components/TitleTransferPanel/TitleTransferPanelContent/TitleTransferPanelContent.tsx]: just let it throw if you are not handling, dont do anything and the error will bubble up

File: src/components/TitleTransferPanel/TitleTransferPanelContent/TitleTransferPanelContent.tsx [hunk 19]
```diff
@@ -1,23 +1,34 @@
...
+      const address = await getTokenOwner({ document });
+      setTokenOwnerAddress(address);
+    } finally {
+      // prevent code smell in sonar
+    }
+  };
+  fetchTokenOwner();
```
Comment (yehjxraymond) [inline src/components/TitleTransferPanel/TitleTransferPanelContent/TitleTransferPanelContent.tsx]: do you want to put this into useEffect(()=> {somefunction}, [document]) so that it runs only once everytime document change instead of running once per rerender?

**Review by yehjxraymond — CHANGES_REQUESTED** [review]

File: src/components/TitleTransferPanel/TitleTransferPanelContent/TitleTransferPanelContent.tsx [hunk 20]
```diff
@@ -12,15 +12,15 @@ interface TitleTransferPanelContentProps {
 export const TitleTransferPanelContent = ({ document }: TitleTransferPanelContentProps) => {
   const [tokenOwnerAddress, setTokenOwnerAddress] = useState("");
   const { holderAddress, beneficiaryAddress } = useEscrowContractUsers({ escrowContractAddress: tokenOwnerAddress });
-  const fetchTokenOwner = async () => {
-    try {
+
+  useEffect(() => {
+    const fetchTokenOwner = async () => {
```
Comment (yehjxraymond) [inline src/components/TitleTransferPanel/TitleTransferPanelContent/TitleTransferPanelContent.tsx]: You can put this outside the useEffect and only call it with fetchTokenOwner inside the useEffect

Comment (simboonlong) [reply src/components/TitleTransferPanel/TitleTransferPanelContent/TitleTransferPanelContent.tsx]: oh i tried that but lint gimme this hence i put inside.

Screenshot 2020-03-26 at 2 02 30 PM

Comment (yehjxraymond) [reply src/components/TitleTransferPanel/TitleTransferPanelContent/TitleTransferPanelContent.tsx]: haha make the function signature of fetchTokenOwner to take the document in as a param. 

const fetchTokenOwner = async (document) => {
  const address = await getTokenOwner({ document });
  setTokenOwnerAddress(address);
}

**Review by yehjxraymond — APPROVED** [review]
image


LGTM (=
